import { Delete, Edit } from "../Reviews/ReviewsIcons";
export const ManageUserData = [
  {
    key: "1",
    userId: "#1234",
    userType: "Normal",
    userName: "Savannah Nguyen",
    email: "vuhaithuongnute@gmail.com",
    totalSpent: "$ 23987",
    orders: "28",
    city: "Lahore",
    dateTime: "10-6-23",
    action1: <Edit />,
    action2: <Delete />,
  },
  {
    key: "2",
    userId: "#1345",
    userType: "Seller",
    product: "Smartphone",
    userName: "Marvin McKinney",
    email: "binhan628@gmail.com",
    totalSpent: "$ 21567",
    orders: "45",
    city: "Karachi",
    dateTime: "08-11-23",
    action1: <Edit />,
    action2: <Delete />,
  },
  {
    key: "3",
    userId: "#1654",
    userType: "Normal",
    userName: "Marvin McKinney",
    email: "trungkienspktnd@gamail.com",
    totalSpent: "$ 19872",
    orders: "34",
    city: "Gujranwala",
    dateTime: "05-27-22",
    action1: <Edit />,
    action2: <Delete />,
  },
  {
    key: "4",
    userId: "#5634",
    userType: "Normal",
    userName: "Kristin Watson",
    email: "thuhang.nute@gmail.com",
    totalSpent: "$ 17996",
    orders: "33",
    city: "Faisalabad",
    dateTime: "05-27-23",
    action1: <Edit />,
    action2: <Delete />,
  },
];
