export const OrdersTableData = [
  {
    key: "1",
    listingId: "#1234",
    orderType: "Sale",
    sellerName: "Courney Henry",
    category: "Dress",
    city: "Faislabad",
    dateTime: "10-6-23 - 10:32 PM",
    paymentStatus: "Completed",
    orderStaus: "Completed",
  },
  {
    key: "2",
    listingId: "#1212",
    orderType: "Flip",
    sellerName: "Fusy Kawkins",
    category: "Smartphone",
    city: "Lahore",
    dateTime: "03-30-23 - 11:45 PM",
    paymentStatus: "Completed",
    orderStaus: "Completed",
  },
  {
    key: "3",
    listingId: "#1244",
    orderType: "Sale-Flip",
    sellerName: "Marvin McKinney",
    category: "Shoes",
    city: "Islamabad",
    dateTime: "08-11-23 - 09:57 PM",
    paymentStatus: "Rejected",
    orderStaus: "Rejected",
  },
  {
    key: "4",
    listingId: "#1245",
    orderType: "Flip",
    sellerName: "Theresa Webb",
    category: "Accessories",
    city: "Karachi",
    dateTime: "05-27-22 - 10:11 PM",
    paymentStatus: "Completed",
    orderStaus: "Completed",
  },
  {
    key: "5",
    listingId: "#1345",
    orderType: "Sale",
    sellerName: "Devon Lane",
    category: "Dress",
    city: "Multan",
    dateTime: "05-27-23 - 06-43 PM",
    paymentStatus: "Processing",
    orderStaus: "Processing",
  },
];
